import { useEffect, useState } from "react";
import { api, downloadArtifact } from "../lib/api";
import type { ArtifactRecord, RequestError } from "../lib/types";
import { DataTable } from "../components/DataTable";
import { SectionCard } from "../components/SectionCard";

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function ExportsPage() {
  const [artifacts, setArtifacts] = useState<ArtifactRecord[]>([]);
  const [status, setStatus] = useState("Ready.");
  const [error, setError] = useState("");

  async function load() {
    try {
      setArtifacts(await api.exports());
      setError("");
    } catch (err) {
      const requestError = err as RequestError;
      setError(requestError.status === 401 ? "Unauthorized. Provide a valid analyst token." : requestError.message);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function createManagementSummary() {
    setStatus("Generating management summary...");
    const artifact = await api.exportManagementSummary("html");
    const blob = await downloadArtifact(artifact.download_url);
    downloadBlob(blob, `management-summary-${artifact.id}.html`);
    setStatus("Management summary downloaded and recorded.");
    await load();
  }

  async function createBlocklist() {
    setStatus("Generating blocklist export...");
    const artifact = await api.exportBlocklist("csv");
    const blob = await downloadArtifact(artifact.download_url);
    downloadBlob(blob, `blocklist-${artifact.id}.csv`);
    setStatus("Blocklist export downloaded and recorded.");
    await load();
  }

  async function downloadExisting(artifact: ArtifactRecord) {
    const blob = await downloadArtifact(artifact.download_url);
    downloadBlob(blob, `${artifact.artifact_type}-${artifact.id}.${artifact.export_format}`);
  }

  return (
    <div className="page-grid">
      <SectionCard
        title="Exports"
        subtitle="Generate containment and reporting artifacts and keep them auditable."
        actions={
          <div className="button-row">
            <button onClick={createManagementSummary}>Management Summary</button>
            <button onClick={createBlocklist}>IOC / Blocklist</button>
          </div>
        }
      >
        {error ? <div className="error-panel">{error}</div> : null}
        <div className="status-inline">{status}</div>
        <div className="detail-grid">
          <div className="detail-card">
            <strong>Management summary</strong>
            <p>Executive-ready HTML summary of current exposure, detections, and containment posture.</p>
          </div>
          <div className="detail-card">
            <strong>IOC / blocklist export</strong>
            <p>CSV artifact designed for fast handoff into firewall, WAF, or perimeter review workflows.</p>
          </div>
        </div>
      </SectionCard>

      <SectionCard title="Artifact log" subtitle="All generated exports recorded for review and handoff.">
        <DataTable
          rows={artifacts}
          emptyMessage="No artifacts generated yet."
          columns={[
            { key: "type", title: "Type", render: (row) => row.artifact_type },
            { key: "format", title: "Format", render: (row) => row.export_format },
            { key: "by", title: "Generated by", render: (row) => row.generated_by },
            { key: "when", title: "Generated at", render: (row) => new Date(row.generated_at).toLocaleString() },
            {
              key: "download",
              title: "Download",
              render: (row) => <button onClick={() => downloadExisting(row)}>Download</button>,
            },
          ]}
        />
      </SectionCard>
    </div>
  );
}
