apiVersion: v1
kind: Secret
metadata:
  name: {{ include "honeynet.fullname" . }}-secret
  labels:
    {{- include "honeynet.labels" . | nindent 4 }}
type: Opaque
stringData:
  HONEYPOT_INGEST_API_KEY: {{ .Values.api.ingressApiKey | quote }}
  HONEYPOT_ANALYST_BEARER_TOKEN: {{ .Values.api.analystBearerToken | quote }}
  {{- if .Values.postgres.enabled }}
  HONEYPOT_DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s-postgres:5432/%s" .Values.postgres.username .Values.postgres.password (include "honeynet.fullname" .) .Values.postgres.database | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  HONEYPOT_ARTIFACT_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  HONEYPOT_ARTIFACT_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
  {{- end }}
